### ISSUE TITLE
Not useful for ReservedFlashlightSlot by FlipMods

### ISSUE THREAD

**Issue by meBVH** [Wexop/RandomColors#1]
When I hold the flashlight in my hand or hold down 'alt' to retrieve it, the random color light of the flashlight is effective.
But simply press 'F' to turn on the flashlight,  the random color light of the flashlight is useless.

**Comment by Wexop** [comment]
Hey !
What mod are you using for the flashLight input ? I will check that :)

Thanks for the report !

**Comment by miguelguzmanr** [comment]
Really cool mod! Thanks for making this.

> Hey ! What mod are you using for the flashLight input ? I will check that :)

It's this one: [ReservedFlashlightSlot](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedFlashlightSlot/)

**Comment by Wexop** [comment]
Thanks :)

So i checked this, and it seems to be an issue on my mod

If you take a flashlight turned on in your pocket, the light will change to white.

I'll try to fix that soon ! 

Thanks for the report :)
